name: poster
description: 'Mini-social network'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
      sdk: flutter
  flutter_bloc: ^8.1.6
  cupertino_icons: ^1.0.8
  fpdart: ^1.1.0
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  universal_platform: ^1.0.0+1
  streaming_shared_preferences: ^2.0.0
  shared_preferences: ^2.3.2
  json_annotation: ^4.9.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans-VariableFont_YTLC,opsz,wdth,wght.ttf
        - asset: assets/fonts/NunitoSans-Italic-VariableFont_YTLC,opsz,wdth,wght.ttf
          style: italic
